name: Deploy to Railway
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install backend dependencies and run tests
        working-directory: backend
        run: |
          pip install -r requirements.txt
          python manage.py test
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install frontend dependencies and lint
        working-directory: frontend
        run: |
          npm ci
          npm run lint
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy backend service
        run: railway up --service backend
      - name: Deploy frontend service
        run: railway up --service frontend
