name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run backend tests
        run: python manage.py test
        working-directory: backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run frontend lint
        run: npm run lint
        working-directory: frontend

      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/freelance-codex-backend:latest backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/freelance-codex-frontend:latest frontend

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/freelance-codex-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/freelance-codex-frontend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          kubectl apply -f k8s/
